/**
 * Reálne pražské správcovské firmy — verejné údaje z ARES a ich vlastných
 * webov, nazbierané 2026-05-28.
 *
 * Tieto firmy NEDALI SÚHLAS so zaradením do katalógu. Sú importované ako
 * "kandidáti" so `schvaleny: false` — v aplikácii sa zobrazia až keď ich
 * admin ručne schváli v `/admin/spravci`. Pred publikovaním je vhodné firmu
 * osloviť (e-mailom uvedeným na ich webe) so žiadosťou o doplnenie údajov
 * alebo o súhlas s prezentáciou.
 *
 * `kontaktniOsoba` zámerne neuvádza meno konkrétneho zamestnanca. Mená
 * jednateľov, ktoré sú verejne v Obchodnom registri, ponecháme až po
 * onboardingu.
 *
 * `prumerneHodnoceni: 0`, `pocetRecenzi: 0` — žiadne fiktívne recenzie pre
 * reálne firmy.
 */

import type { SpravceSeed } from "./spravci";

const logoBg = (nazev: string, color: string) =>
  `https://ui-avatars.com/api/?name=${encodeURIComponent(nazev)}&background=${color}&color=fff&size=256&bold=true&format=png`;

export const realniSpravciSeed: SpravceSeed[] = [
  {
    slug: "aria-servis",
    nazev: "Aria servis, s.r.o.",
    logo: logoBg("Aria Servis", "1a5cf5"),
    popis:
      "Komplexní správa nemovitostí v Praze a Středočeském kraji s minimální osobní účastí výboru SVJ. Nabízíme účetní servis, ekonomickou a technickou správu, facility management, profesionálního předsedu SVJ a úklidové služby. Důraz klademe na měření kvality procesů přes KPI.",
    regionyPusobnosti: ["Praha 1", "Praha 2", "Praha 3", "Praha 7"],
    pocetDomu: 0,
    pocetJednotek: 0,
    rokZalozeni: 2019,
    sluzby: {
      ucetniSprava: true,
      technickaSprava: true,
      havarijniSluzba: true,
      onlinePortal: true,
      onlineHlasovani: false,
      zkRekonstrukce: false,
      zkDotace: false,
      zkUvery: false,
      pravniPoradenstvi: false,
    },
    cenaOd: 0,
    cenaDo: 0,
    kontaktniOsoba: "Kontaktní e-mail / telefon",
    email: "info@ariaservis.cz",
    telefon: "+420 739 008 097",
    web: "https://www.sprava-nemovitosti-praha.eu",
    adresa: "Kaprova 42/14, 110 00 Praha 1",
    reference: [],
    overeny: false,
    premium: false,
    prumerneHodnoceni: 0,
    pocetRecenzi: 0,
  },
  {
    slug: "avema-praha",
    nazev: "AVEMA Praha s.r.o.",
    logo: logoBg("Avema Praha", "0ea5e9"),
    popis:
      "Komplexní služby správy nemovitostí pro SVJ a bytová družstva v Praze a Středočeském kraji. Spravujeme přes 70 objektů a více než 6 500 bytových jednotek. Zajišťujeme ekonomickou i technickou správu, údržbu, úklid, havarijní pohotovostní službu 24/7 a online klientskou zónu s dokumenty.",
    regionyPusobnosti: ["Praha 10", "Praha 9", "Praha 4", "Praha 3"],
    pocetDomu: 70,
    pocetJednotek: 6500,
    rokZalozeni: 2009,
    sluzby: {
      ucetniSprava: true,
      technickaSprava: true,
      havarijniSluzba: true,
      onlinePortal: true,
      onlineHlasovani: false,
      zkRekonstrukce: false,
      zkDotace: false,
      zkUvery: false,
      pravniPoradenstvi: true,
    },
    cenaOd: 0,
    cenaDo: 0,
    kontaktniOsoba: "Kontaktní e-mail / telefon",
    email: "avema@avema.cz",
    telefon: "+420 608 093 253",
    web: "https://www.avema.cz",
    adresa: "Flájská 3214/8, 100 00 Praha 10 - Strašnice",
    reference: [],
    overeny: false,
    premium: false,
    prumerneHodnoceni: 0,
    pocetRecenzi: 0,
  },
  {
    slug: "jivis",
    nazev: "JiViŠ, s.r.o.",
    logo: logoBg("JiViS", "16a34a"),
    popis:
      "Specialista na správu bytových domů pro SVJ a bytová družstva s více než 20 lety zkušeností. Spravujeme přes 280 bytových domů a 8 000 bytových jednotek v Praze a okolí. Nabízíme technickou správu, vedení účetnictví, profesionálního předsedu SVJ, úklid, údržbu zeleně, pojištění nemovitostí a tvorbu webů pro SVJ.",
    regionyPusobnosti: ["Praha 9", "Praha 3", "Praha 8", "Praha 10", "Praha 14"],
    pocetDomu: 280,
    pocetJednotek: 8000,
    rokZalozeni: 2004,
    sluzby: {
      ucetniSprava: true,
      technickaSprava: true,
      havarijniSluzba: false,
      onlinePortal: false,
      onlineHlasovani: false,
      zkRekonstrukce: false,
      zkDotace: false,
      zkUvery: false,
      pravniPoradenstvi: false,
    },
    cenaOd: 0,
    cenaDo: 0,
    kontaktniOsoba: "Kontaktní e-mail / telefon",
    email: "jivis@jivis.cz",
    telefon: "+420 266 310 266",
    web: "https://www.jivis.cz",
    adresa: "Poděbradská 489/116, 198 00 Praha 9",
    reference: [],
    overeny: false,
    premium: false,
    prumerneHodnoceni: 0,
    pocetRecenzi: 0,
  },
  {
    slug: "man-praha",
    nazev: "M.A.N., spol. s r.o.",
    logo: logoBg("MAN Praha", "475569"),
    popis:
      "Komplexní služby správy nemovitostí pro SVJ a bytová družstva. Na trhu působíme od roku 1996, tedy více než 28 let. Nabízíme účetní a technickou správu, údržbu, havarijní službu (voda, plyn, topení, elektro, zámečník, sklenář) a online klientský portál Správce24.",
    regionyPusobnosti: ["Praha 9", "Praha 3", "Praha 8", "Praha 14"],
    pocetDomu: 0,
    pocetJednotek: 0,
    rokZalozeni: 1996,
    sluzby: {
      ucetniSprava: true,
      technickaSprava: true,
      havarijniSluzba: true,
      onlinePortal: true,
      onlineHlasovani: false,
      zkRekonstrukce: false,
      zkDotace: false,
      zkUvery: false,
      pravniPoradenstvi: false,
    },
    cenaOd: 0,
    cenaDo: 0,
    kontaktniOsoba: "Kontaktní e-mail / telefon",
    email: "manpraha@manpraha.cz",
    telefon: "+420 281 932 598",
    web: "https://www.manpraha.cz",
    adresa: "Žitenická 871/1, 190 00 Praha 9 - Prosek",
    reference: [],
    overeny: false,
    premium: false,
    prumerneHodnoceni: 0,
    pocetRecenzi: 0,
  },
  {
    slug: "mitom",
    nazev: "Mitom - správa nemovitostí, s.r.o.",
    logo: logoBg("Mitom", "ea580c"),
    popis:
      "Společnost s více než dvacetiletou zkušeností (založena 2002) poskytující komplexní služby správy nemovitostí pro SVJ. Pokrýváme právní, provozní, ekonomický, účetní a technický servis s důrazem na minimalizaci nákladů a nonstop bezpečnostní podporu. Klienti mají přístup k online portálu domsys.eu.",
    regionyPusobnosti: ["Praha 2", "Praha 3", "Praha 10", "Praha 4"],
    pocetDomu: 0,
    pocetJednotek: 0,
    rokZalozeni: 2002,
    sluzby: {
      ucetniSprava: true,
      technickaSprava: true,
      havarijniSluzba: true,
      onlinePortal: true,
      onlineHlasovani: false,
      zkRekonstrukce: false,
      zkDotace: false,
      zkUvery: false,
      pravniPoradenstvi: true,
    },
    cenaOd: 0,
    cenaDo: 0,
    kontaktniOsoba: "Kontaktní e-mail / telefon",
    email: "info@mitom.cz",
    telefon: "+420 224 242 653",
    web: "https://www.mitom.cz",
    adresa: "Jana Masaryka 364/23, 120 00 Praha 2 - Vinohrady",
    reference: [],
    overeny: false,
    premium: false,
    prumerneHodnoceni: 0,
    pocetRecenzi: 0,
  },
  {
    slug: "pro-svj",
    nazev: "PRO SVJ s.r.o.",
    logo: logoBg("Pro SVJ", "9333ea"),
    popis:
      "Správa bytových domů ve vlastnictví společenství vlastníků a bytových družstev, působíme od roku 2011. Spravujeme domy všech velikostí, typů a stáří. Nabízíme vedení účetnictví, správu nemovitostí, rozúčtování nákladů a předpis záloh. Spolupracujeme dlouhodobě i s institucemi veřejného sektora.",
    regionyPusobnosti: ["Praha 9", "Praha 14", "Praha 10"],
    pocetDomu: 0,
    pocetJednotek: 0,
    rokZalozeni: 2011,
    sluzby: {
      ucetniSprava: true,
      technickaSprava: true,
      havarijniSluzba: false,
      onlinePortal: false,
      onlineHlasovani: false,
      zkRekonstrukce: false,
      zkDotace: false,
      zkUvery: false,
      pravniPoradenstvi: false,
    },
    cenaOd: 0,
    cenaDo: 0,
    kontaktniOsoba: "Kontaktní e-mail / telefon",
    email: "sprava@pro-svj.cz",
    telefon: "+420 777 588 998",
    web: "https://pro-svj.cz",
    adresa: "Jansova 650, 198 00 Praha 9 - Hostavice",
    reference: [],
    overeny: false,
    premium: false,
    prumerneHodnoceni: 0,
    pocetRecenzi: 0,
  },
  {
    slug: "svj-compass",
    nazev: "SVJ Compass s.r.o.",
    logo: logoBg("SVJ Compass", "0891b2"),
    popis:
      "Profesionální správa SVJ v Praze a okolí. Zakládáme si na kvalitních službách, transparentní komunikaci a srozumitelných výstupech. Nabízíme komplexní správu, běžnou údržbu, výkon funkce předsedy SVJ, konzultace a projektové řízení rekonstrukcí.",
    regionyPusobnosti: ["Praha 4", "Praha 2", "Praha 10"],
    pocetDomu: 0,
    pocetJednotek: 0,
    rokZalozeni: 2017,
    sluzby: {
      ucetniSprava: true,
      technickaSprava: true,
      havarijniSluzba: false,
      onlinePortal: false,
      onlineHlasovani: false,
      zkRekonstrukce: true,
      zkDotace: false,
      zkUvery: false,
      pravniPoradenstvi: false,
    },
    cenaOd: 230,
    cenaDo: 360,
    kontaktniOsoba: "Kontaktní e-mail / telefon",
    email: "info@svjcompass.cz",
    telefon: "+420 720 761 847",
    web: "https://svjcompass.cz",
    adresa: "Mikuláše z Husi 736/8, 140 00 Praha 4 - Nusle",
    reference: [],
    overeny: false,
    premium: false,
    prumerneHodnoceni: 0,
    pocetRecenzi: 0,
  },
];
