/**
 * Demo dáta — 30 pražských správcov SVJ a BD.
 *
 * UPOZORNENIE: Všetky názvy firiem, kontakty a údaje sú FIKTÍVNE a slúžia
 * iba na ukážku MVP. Akákoľvek podobnosť so skutočnými firmami je náhodná.
 * Reálne firmy sa naplnia až po onboardingu / scrapingu verejných registrov
 * s ich súhlasom.
 */

export type SpravceSeed = {
  slug: string;
  nazev: string;
  logo: string;
  popis: string;
  regionyPusobnosti: string[];
  pocetDomu: number;
  pocetJednotek: number;
  rokZalozeni: number;
  sluzby: {
    ucetniSprava: boolean;
    technickaSprava: boolean;
    havarijniSluzba: boolean;
    onlinePortal: boolean;
    onlineHlasovani: boolean;
    zkRekonstrukce: boolean;
    zkDotace: boolean;
    zkUvery: boolean;
    pravniPoradenstvi: boolean;
  };
  cenaOd: number;
  cenaDo: number;
  kontaktniOsoba: string;
  email: string;
  telefon: string;
  web: string;
  adresa: string;
  reference: string[];
  overeny: boolean;
  premium: boolean;
  prumerneHodnoceni: number;
  pocetRecenzi: number;
};

const prahyVsechny = [
  "Praha 1", "Praha 2", "Praha 3", "Praha 4", "Praha 5",
  "Praha 6", "Praha 7", "Praha 8", "Praha 9", "Praha 10",
];

const logoBg = (nazev: string, color: string) =>
  `https://ui-avatars.com/api/?name=${encodeURIComponent(nazev)}&background=${color}&color=fff&size=256&bold=true&format=png`;

export const spravciSeed: SpravceSeed[] = [
  {
    slug: "dum-pod-spravou",
    nazev: "Dům pod správou s.r.o.",
    logo: logoBg("Dum Spravou", "1a5cf5"),
    popis:
      "Specializujeme se na komplexní správu SVJ a bytových domů v Praze. Klademe důraz na transparentní účetnictví, rychlou komunikaci a online přístup k veškerým dokumentům 24/7. S našimi klienty fungujeme jako partneři — ne jako anonymní administrátoři.",
    regionyPusobnosti: ["Praha 1", "Praha 2", "Praha 3", "Praha 7", "Praha 8"],
    pocetDomu: 112,
    pocetJednotek: 3840,
    rokZalozeni: 2009,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: true, onlineHlasovani: true, zkRekonstrukce: true, zkDotace: true, zkUvery: true, pravniPoradenstvi: true },
    cenaOd: 180,
    cenaDo: 280,
    kontaktniOsoba: "Ing. Petra Novotná",
    email: "info@dumpodspravou.demo",
    telefon: "+420 234 567 890",
    web: "https://dumpodspravou.demo",
    adresa: "Vinohradská 22, 120 00 Praha 2",
    reference: [
      "SVJ Vinohradská 47 — 38 jednotek, spolupráce od 2015",
      "SVJ Belgická 22 — 22 jednotek, kompletní rekonstrukce 2021",
      "BD Karlínské náměstí 8 — 64 jednotek",
    ],
    overeny: true, premium: true,
    prumerneHodnoceni: 4.7, pocetRecenzi: 28,
  },
  {
    slug: "spravbyt-praha",
    nazev: "SpravByt Praha a.s.",
    logo: logoBg("SpravByt", "0ea5e9"),
    popis:
      "Patříme mezi největší pražské správce s vlastním právním a technickým oddělením. Pokrýváme celou Prahu a část středočeského kraje. Klientům nabízíme vlastní portál se schůzemi online.",
    regionyPusobnosti: prahyVsechny,
    pocetDomu: 420,
    pocetJednotek: 12500,
    rokZalozeni: 1998,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: true, onlineHlasovani: true, zkRekonstrukce: true, zkDotace: true, zkUvery: true, pravniPoradenstvi: true },
    cenaOd: 150,
    cenaDo: 240,
    kontaktniOsoba: "Mgr. Tomáš Procházka",
    email: "info@spravbyt-praha.demo",
    telefon: "+420 222 333 444",
    web: "https://spravbyt-praha.demo",
    adresa: "Bělehradská 110, 120 00 Praha 2",
    reference: [
      "Spravujeme přes 12 000 jednotek v Praze",
      "Více než 25 let na trhu",
    ],
    overeny: true, premium: true,
    prumerneHodnoceni: 4.5, pocetRecenzi: 64,
  },
  {
    slug: "moderni-sprava",
    nazev: "Moderní správa SVJ s.r.o.",
    logo: logoBg("Moderni Sprava", "16a34a"),
    popis:
      "Mladá firma s digitálním přístupem. Vše vedeme paperless, máme vlastní mobilní aplikaci pro vlastníky, online hlasování i digitální pasportizaci.",
    regionyPusobnosti: ["Praha 5", "Praha 6", "Praha 13", "Praha 4"],
    pocetDomu: 48,
    pocetJednotek: 1620,
    rokZalozeni: 2019,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: true, onlineHlasovani: true, zkRekonstrukce: true, zkDotace: false, zkUvery: false, pravniPoradenstvi: true },
    cenaOd: 190,
    cenaDo: 290,
    kontaktniOsoba: "Jakub Horáček",
    email: "info@modernisprava.demo",
    telefon: "+420 777 123 456",
    web: "https://modernisprava.demo",
    adresa: "Plzeňská 130, 150 00 Praha 5",
    reference: ["SVJ Anděl Park — 84 jednotek, smart home integrace"],
    overeny: true, premium: true,
    prumerneHodnoceni: 4.8, pocetRecenzi: 19,
  },
  {
    slug: "byt-servis-cz",
    nazev: "ByT Servis CZ s.r.o.",
    logo: logoBg("ByT Servis", "dc2626"),
    popis: "Tradiční rodinná firma s důrazem na osobní přístup. Zaměřujeme se na menší a střední domy v centru Prahy.",
    regionyPusobnosti: ["Praha 1", "Praha 2", "Praha 3"],
    pocetDomu: 64,
    pocetJednotek: 1280,
    rokZalozeni: 2004,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: false, onlineHlasovani: false, zkRekonstrukce: true, zkDotace: false, zkUvery: true, pravniPoradenstvi: false },
    cenaOd: 160,
    cenaDo: 220,
    kontaktniOsoba: "Václav Dvořák",
    email: "info@bytservis.demo",
    telefon: "+420 224 815 622",
    web: "https://bytservis.demo",
    adresa: "Národní 20, 110 00 Praha 1",
    reference: ["Více než 60 historických domů v centru"],
    overeny: true, premium: false,
    prumerneHodnoceni: 4.3, pocetRecenzi: 22,
  },
  {
    slug: "klidne-bydleni",
    nazev: "Klidné bydlení s.r.o.",
    logo: logoBg("Klidne Bydleni", "9333ea"),
    popis: "Naším cílem je, abyste o správě domu nemuseli přemýšlet. Komplexní servis na klíč včetně dotačního poradenství.",
    regionyPusobnosti: ["Praha 4", "Praha 10", "Praha 11", "Praha 12"],
    pocetDomu: 92,
    pocetJednotek: 2840,
    rokZalozeni: 2012,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: true, onlineHlasovani: false, zkRekonstrukce: true, zkDotace: true, zkUvery: true, pravniPoradenstvi: true },
    cenaOd: 170,
    cenaDo: 250,
    kontaktniOsoba: "Ing. Marie Krejčová",
    email: "info@klidnebydleni.demo",
    telefon: "+420 261 213 555",
    web: "https://klidnebydleni.demo",
    adresa: "Roztylská 19, 148 00 Praha 4",
    reference: ["SVJ Chodov — 156 jednotek, úspěšná dotace NZÚ"],
    overeny: true, premium: true,
    prumerneHodnoceni: 4.6, pocetRecenzi: 35,
  },
  {
    slug: "ad-rem-real",
    nazev: "Ad Rem Real s.r.o.",
    logo: logoBg("Ad Rem Real", "ea580c"),
    popis: "Specialisté na velké panelové domy a komplexy 100+ jednotek. Vlastní havarijní služba 24/7 v celé Praze.",
    regionyPusobnosti: ["Praha 8", "Praha 9", "Praha 14", "Praha 18"],
    pocetDomu: 156,
    pocetJednotek: 6420,
    rokZalozeni: 2005,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: true, onlineHlasovani: true, zkRekonstrukce: true, zkDotace: true, zkUvery: true, pravniPoradenstvi: true },
    cenaOd: 140,
    cenaDo: 210,
    kontaktniOsoba: "Pavel Říha",
    email: "info@adremreal.demo",
    telefon: "+420 283 880 123",
    web: "https://adremreal.demo",
    adresa: "Sokolovská 365, 180 00 Praha 8",
    reference: ["BD Černý Most — 220 jednotek", "BD Prosek — 184 jednotek"],
    overeny: true, premium: true,
    prumerneHodnoceni: 4.4, pocetRecenzi: 48,
  },
  {
    slug: "domeo-spravce",
    nazev: "Domeo Správce s.r.o.",
    logo: logoBg("Domeo", "0891b2"),
    popis: "Digitální správa s důrazem na transparentnost. Každý vlastník vidí v reálném čase stav účtů i probíhajících oprav.",
    regionyPusobnosti: ["Praha 5", "Praha 6", "Praha 13", "Praha 17"],
    pocetDomu: 38,
    pocetJednotek: 1180,
    rokZalozeni: 2020,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: false, onlinePortal: true, onlineHlasovani: true, zkRekonstrukce: true, zkDotace: false, zkUvery: false, pravniPoradenstvi: false },
    cenaOd: 200,
    cenaDo: 300,
    kontaktniOsoba: "Lukáš Beneš",
    email: "info@domeo.demo",
    telefon: "+420 730 555 200",
    web: "https://domeo.demo",
    adresa: "Evropská 423, 160 00 Praha 6",
    reference: ["SVJ Dejvice Square — moderní novostavba 64 j."],
    overeny: true, premium: false,
    prumerneHodnoceni: 4.7, pocetRecenzi: 12,
  },
  {
    slug: "bytova-druzina",
    nazev: "Bytová družina s.r.o.",
    logo: logoBg("Bytova Druzina", "7c3aed"),
    popis: "Správa SVJ s lidskou tváří. Známe každého klienta osobně a jsme dostupní telefonicky kdykoliv ve všední dny.",
    regionyPusobnosti: ["Praha 6", "Praha 7", "Praha 8"],
    pocetDomu: 56,
    pocetJednotek: 1480,
    rokZalozeni: 2011,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: false, onlineHlasovani: false, zkRekonstrukce: true, zkDotace: true, zkUvery: false, pravniPoradenstvi: true },
    cenaOd: 175,
    cenaDo: 245,
    kontaktniOsoba: "Ing. Hana Šimková",
    email: "info@bytovadruzina.demo",
    telefon: "+420 233 322 100",
    web: "https://bytovadruzina.demo",
    adresa: "Bubenská 8, 170 00 Praha 7",
    reference: ["Letenské sady — 4 SVJ, dlouhodobá spolupráce"],
    overeny: true, premium: false,
    prumerneHodnoceni: 4.5, pocetRecenzi: 24,
  },
  {
    slug: "svj-partner",
    nazev: "SVJ Partner s.r.o.",
    logo: logoBg("SVJ Partner", "f59e0b"),
    popis: "Partnerem pro vaše SVJ od založení až po každodenní provoz. Pomáháme i s přechodem od jiného správce.",
    regionyPusobnosti: ["Praha 9", "Praha 10", "Praha 14", "Praha 15"],
    pocetDomu: 78,
    pocetJednotek: 2180,
    rokZalozeni: 2008,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: true, onlineHlasovani: true, zkRekonstrukce: true, zkDotace: true, zkUvery: true, pravniPoradenstvi: true },
    cenaOd: 165,
    cenaDo: 230,
    kontaktniOsoba: "Mgr. Jan Müller",
    email: "info@svjpartner.demo",
    telefon: "+420 274 819 333",
    web: "https://svjpartner.demo",
    adresa: "Kolbenova 882, 190 00 Praha 9",
    reference: ["BD Vysočany Garden — 96 jednotek"],
    overeny: true, premium: true,
    prumerneHodnoceni: 4.6, pocetRecenzi: 41,
  },
  {
    slug: "praha-byty-spravce",
    nazev: "Praha Byty Správce s.r.o.",
    logo: logoBg("Praha Byty", "059669"),
    popis: "Tradiční pražský správce od roku 1995. Specializace na panelové i cihlové domy postavené v 60.–90. letech.",
    regionyPusobnosti: ["Praha 4", "Praha 11", "Praha 12"],
    pocetDomu: 220,
    pocetJednotek: 7840,
    rokZalozeni: 1995,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: true, onlineHlasovani: false, zkRekonstrukce: true, zkDotace: true, zkUvery: true, pravniPoradenstvi: false },
    cenaOd: 130,
    cenaDo: 200,
    kontaktniOsoba: "Ing. Karel Vondráček",
    email: "info@prahabyty.demo",
    telefon: "+420 244 469 999",
    web: "https://prahabyty.demo",
    adresa: "Roztylská 31, 148 00 Praha 4",
    reference: ["Háje — 14 panelových domů", "Jižní Město — 22 SVJ"],
    overeny: true, premium: false,
    prumerneHodnoceni: 4.1, pocetRecenzi: 58,
  },
  {
    slug: "central-real-cz",
    nazev: "Central Real CZ s.r.o.",
    logo: logoBg("Central Real", "be185d"),
    popis: "Premium správa luxusních nemovitostí v historickém centru Prahy. Diskrétnost, kvalita, individuální přístup.",
    regionyPusobnosti: ["Praha 1", "Praha 2"],
    pocetDomu: 28,
    pocetJednotek: 320,
    rokZalozeni: 2014,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: true, onlineHlasovani: true, zkRekonstrukce: true, zkDotace: false, zkUvery: false, pravniPoradenstvi: true },
    cenaOd: 280,
    cenaDo: 480,
    kontaktniOsoba: "Mgr. Eliška Černá",
    email: "info@centralreal.demo",
    telefon: "+420 222 100 100",
    web: "https://centralreal.demo",
    adresa: "Pařížská 7, 110 00 Praha 1",
    reference: ["SVJ Pařížská — památkově chráněný dům 1898"],
    overeny: true, premium: true,
    prumerneHodnoceni: 4.9, pocetRecenzi: 11,
  },
  {
    slug: "spravce365",
    nazev: "Správce365 s.r.o.",
    logo: logoBg("Spravce 365", "0284c7"),
    popis: "365 dní v roce. Vlastní výjezdová technická služba a online portál pro vlastníky.",
    regionyPusobnosti: ["Praha 4", "Praha 5", "Praha 13", "Praha 16"],
    pocetDomu: 84,
    pocetJednotek: 2640,
    rokZalozeni: 2016,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: true, onlineHlasovani: true, zkRekonstrukce: false, zkDotace: false, zkUvery: false, pravniPoradenstvi: true },
    cenaOd: 185,
    cenaDo: 265,
    kontaktniOsoba: "Ing. Roman Lukáš",
    email: "info@spravce365.demo",
    telefon: "+420 251 555 365",
    web: "https://spravce365.demo",
    adresa: "Stodůlecká 15, 155 00 Praha 13",
    reference: ["BD Stodůlky — 142 jednotek"],
    overeny: true, premium: true,
    prumerneHodnoceni: 4.5, pocetRecenzi: 32,
  },
  {
    slug: "bona-domus",
    nazev: "Bona Domus s.r.o.",
    logo: logoBg("Bona Domus", "65a30d"),
    popis: "Latinsky „dobrý dům“. Nabízíme férové ceny a profesionální správu pro střední domy 20–80 jednotek.",
    regionyPusobnosti: ["Praha 3", "Praha 10", "Praha 14"],
    pocetDomu: 62,
    pocetJednotek: 1840,
    rokZalozeni: 2013,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: true, onlineHlasovani: false, zkRekonstrukce: true, zkDotace: true, zkUvery: false, pravniPoradenstvi: false },
    cenaOd: 155,
    cenaDo: 215,
    kontaktniOsoba: "Jana Pokorná",
    email: "info@bonadomus.demo",
    telefon: "+420 222 731 010",
    web: "https://bonadomus.demo",
    adresa: "Olšanská 7, 130 00 Praha 3",
    reference: ["SVJ Žižkov — 8 domů v lokalitě"],
    overeny: true, premium: false,
    prumerneHodnoceni: 4.4, pocetRecenzi: 26,
  },
  {
    slug: "spravbyt-classic",
    nazev: "SprávByt Classic s.r.o.",
    logo: logoBg("Classic", "475569"),
    popis: "Klasická správa bez zbytečných vychytávek. Spolehlivá, levná, dostupná telefonicky.",
    regionyPusobnosti: ["Praha 9", "Praha 14", "Praha 18", "Praha 19"],
    pocetDomu: 112,
    pocetJednotek: 3420,
    rokZalozeni: 2001,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: false, onlineHlasovani: false, zkRekonstrukce: true, zkDotace: false, zkUvery: false, pravniPoradenstvi: false },
    cenaOd: 110,
    cenaDo: 170,
    kontaktniOsoba: "Bohuslav Sedláček",
    email: "info@spravbyt-classic.demo",
    telefon: "+420 283 882 200",
    web: "https://spravbyt-classic.demo",
    adresa: "Klíčovská 32, 190 00 Praha 9",
    reference: ["Letňany, Kbely — 18 panelových domů"],
    overeny: false, premium: false,
    prumerneHodnoceni: 3.9, pocetRecenzi: 38,
  },
  {
    slug: "real-management-praha",
    nazev: "Real Management Praha s.r.o.",
    logo: logoBg("Real Management", "991b1b"),
    popis: "Profesionální správa nemovitostí. Tým 24 zaměstnanců včetně 3 právníků a 2 účetních specialistů.",
    regionyPusobnosti: prahyVsechny,
    pocetDomu: 184,
    pocetJednotek: 5320,
    rokZalozeni: 2007,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: true, onlineHlasovani: true, zkRekonstrukce: true, zkDotace: true, zkUvery: true, pravniPoradenstvi: true },
    cenaOd: 175,
    cenaDo: 260,
    kontaktniOsoba: "JUDr. Petr Havel",
    email: "info@realmanagement.demo",
    telefon: "+420 226 211 211",
    web: "https://realmanagement.demo",
    adresa: "Klimentská 36, 110 00 Praha 1",
    reference: ["Komplexní právní servis pro 180+ SVJ"],
    overeny: true, premium: true,
    prumerneHodnoceni: 4.6, pocetRecenzi: 52,
  },
  {
    slug: "abys-bydlel",
    nazev: "Abys Bydlel s.r.o.",
    logo: logoBg("Abys Bydlel", "db2777"),
    popis: "Mladá firma se zaměřením na novostavby a developerské projekty. Pomáháme s předáním domu od developera.",
    regionyPusobnosti: ["Praha 5", "Praha 9", "Praha 10"],
    pocetDomu: 32,
    pocetJednotek: 1240,
    rokZalozeni: 2021,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: false, onlinePortal: true, onlineHlasovani: true, zkRekonstrukce: false, zkDotace: false, zkUvery: false, pravniPoradenstvi: true },
    cenaOd: 210,
    cenaDo: 290,
    kontaktniOsoba: "Tereza Marková",
    email: "info@abysbydlel.demo",
    telefon: "+420 605 333 222",
    web: "https://abysbydlel.demo",
    adresa: "Karla Engliše 6, 150 00 Praha 5",
    reference: ["SVJ Smíchov City — novostavba 2022"],
    overeny: true, premium: false,
    prumerneHodnoceni: 4.7, pocetRecenzi: 14,
  },
  {
    slug: "prazsky-dum",
    nazev: "Pražský dům s.r.o.",
    logo: logoBg("Prazsky Dum", "4338ca"),
    popis: "Lokální správce s 20letou tradicí. Známe pražské reálie, úředníky i řemeslníky.",
    regionyPusobnosti: ["Praha 4", "Praha 10"],
    pocetDomu: 72,
    pocetJednotek: 2120,
    rokZalozeni: 2003,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: false, onlineHlasovani: false, zkRekonstrukce: true, zkDotace: true, zkUvery: true, pravniPoradenstvi: false },
    cenaOd: 145,
    cenaDo: 205,
    kontaktniOsoba: "Ing. Martin Kovář",
    email: "info@prazskydum.demo",
    telefon: "+420 272 711 099",
    web: "https://prazskydum.demo",
    adresa: "Záběhlická 88, 106 00 Praha 10",
    reference: ["SVJ Spořilov — 12 domů v lokalitě"],
    overeny: true, premium: false,
    prumerneHodnoceni: 4.3, pocetRecenzi: 29,
  },
  {
    slug: "spravce-na-klic",
    nazev: "Správce na klíč s.r.o.",
    logo: logoBg("Na Klic", "0d9488"),
    popis: "Kompletní servis na klíč — od pravidelných schůzí přes rekonstrukce po vyřízení dotací NZÚ a OPŽP.",
    regionyPusobnosti: ["Praha 2", "Praha 3", "Praha 8", "Praha 10"],
    pocetDomu: 54,
    pocetJednotek: 1640,
    rokZalozeni: 2015,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: true, onlineHlasovani: true, zkRekonstrukce: true, zkDotace: true, zkUvery: true, pravniPoradenstvi: true },
    cenaOd: 195,
    cenaDo: 285,
    kontaktniOsoba: "Ing. Lucie Vávrová",
    email: "info@spravcenaklic.demo",
    telefon: "+420 222 522 100",
    web: "https://spravcenaklic.demo",
    adresa: "Korunní 88, 130 00 Praha 3",
    reference: ["6 úspěšných žádostí NZÚ v hodnotě 28M Kč"],
    overeny: true, premium: true,
    prumerneHodnoceni: 4.8, pocetRecenzi: 18,
  },
  {
    slug: "byt-asistent",
    nazev: "Byt Asistent s.r.o.",
    logo: logoBg("Byt Asistent", "ca8a04"),
    popis: "Asistujeme předsedovi SVJ — neřídíme za vás, ale jsme tu kdykoliv potřebujete. Vhodné pro SVJ s aktivním předsedou.",
    regionyPusobnosti: ["Praha 6", "Praha 7", "Praha 8", "Praha 9"],
    pocetDomu: 44,
    pocetJednotek: 1180,
    rokZalozeni: 2017,
    sluzby: { ucetniSprava: true, technickaSprava: false, havarijniSluzba: false, onlinePortal: true, onlineHlasovani: true, zkRekonstrukce: false, zkDotace: false, zkUvery: false, pravniPoradenstvi: true },
    cenaOd: 95,
    cenaDo: 150,
    kontaktniOsoba: "Mgr. Adam Beneš",
    email: "info@bytasistent.demo",
    telefon: "+420 731 800 100",
    web: "https://bytasistent.demo",
    adresa: "Argentinská 14, 170 00 Praha 7",
    reference: ["Levný účetní servis pro 40+ menších SVJ"],
    overeny: true, premium: false,
    prumerneHodnoceni: 4.4, pocetRecenzi: 21,
  },
  {
    slug: "domus-pragensis",
    nazev: "Domus Pragensis s.r.o.",
    logo: logoBg("Domus Pragensis", "713f12"),
    popis: "Specialisté na památkově chráněné domy v Praze 1 a 2. Spolupracujeme s NPÚ a magistrátem.",
    regionyPusobnosti: ["Praha 1", "Praha 2", "Praha 3"],
    pocetDomu: 38,
    pocetJednotek: 620,
    rokZalozeni: 2010,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: true, onlineHlasovani: false, zkRekonstrukce: true, zkDotace: true, zkUvery: true, pravniPoradenstvi: true },
    cenaOd: 240,
    cenaDo: 380,
    kontaktniOsoba: "Ing. arch. Klára Tichá",
    email: "info@domuspragensis.demo",
    telefon: "+420 224 218 218",
    web: "https://domuspragensis.demo",
    adresa: "Maiselova 8, 110 00 Praha 1",
    reference: ["12 památkově chráněných domů, rekonstrukce s NPÚ"],
    overeny: true, premium: true,
    prumerneHodnoceni: 4.7, pocetRecenzi: 15,
  },
  {
    slug: "eko-byty",
    nazev: "EkoByty s.r.o.",
    logo: logoBg("Eko Byty", "15803d"),
    popis: "Specializace na energetické úspory, fotovoltaiku a zelená opatření. Vyřizujeme dotace NZÚ pro bytové domy.",
    regionyPusobnosti: ["Praha 4", "Praha 5", "Praha 6", "Praha 10"],
    pocetDomu: 28,
    pocetJednotek: 980,
    rokZalozeni: 2019,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: false, onlinePortal: true, onlineHlasovani: true, zkRekonstrukce: true, zkDotace: true, zkUvery: true, pravniPoradenstvi: false },
    cenaOd: 200,
    cenaDo: 290,
    kontaktniOsoba: "Ing. Filip Zelený",
    email: "info@ekobyty.demo",
    telefon: "+420 720 555 100",
    web: "https://ekobyty.demo",
    adresa: "Pod Krocínkou 28, 190 00 Praha 9",
    reference: ["FVE na 14 bytových domech, 1.2 MWp celkem"],
    overeny: true, premium: true,
    prumerneHodnoceni: 4.9, pocetRecenzi: 9,
  },
  {
    slug: "kompas-spravce",
    nazev: "Kompas Správce s.r.o.",
    logo: logoBg("Kompas", "2563eb"),
    popis: "Nasměrujeme vaše SVJ správným směrem. Strategické plánování, dlouhodobé rezervy, transparentní rozpočty.",
    regionyPusobnosti: ["Praha 4", "Praha 5", "Praha 8"],
    pocetDomu: 66,
    pocetJednotek: 2080,
    rokZalozeni: 2008,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: true, onlineHlasovani: true, zkRekonstrukce: true, zkDotace: true, zkUvery: true, pravniPoradenstvi: true },
    cenaOd: 170,
    cenaDo: 240,
    kontaktniOsoba: "Ing. Ondřej Bárta",
    email: "info@kompas-spravce.demo",
    telefon: "+420 234 222 555",
    web: "https://kompas-spravce.demo",
    adresa: "Novodvorská 14, 142 00 Praha 4",
    reference: ["Pomohli jsme 30 SVJ s tvorbou 20letých plánů oprav"],
    overeny: true, premium: false,
    prumerneHodnoceni: 4.5, pocetRecenzi: 27,
  },
  {
    slug: "spravbyt-extra",
    nazev: "SprávByt Extra s.r.o.",
    logo: logoBg("Extra", "be123c"),
    popis: "Něco navíc — vlastní mobilní aplikace, integrace s bankou, automatické upomínky.",
    regionyPusobnosti: ["Praha 5", "Praha 6", "Praha 13"],
    pocetDomu: 42,
    pocetJednotek: 1480,
    rokZalozeni: 2018,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: false, onlinePortal: true, onlineHlasovani: true, zkRekonstrukce: false, zkDotace: false, zkUvery: false, pravniPoradenstvi: true },
    cenaOd: 195,
    cenaDo: 275,
    kontaktniOsoba: "Ing. Daniel Polák",
    email: "info@spravbytextra.demo",
    telefon: "+420 257 211 700",
    web: "https://spravbytextra.demo",
    adresa: "Plzeňská 1270, 150 00 Praha 5",
    reference: ["Vlastní app s 4500 aktivními uživateli"],
    overeny: true, premium: true,
    prumerneHodnoceni: 4.6, pocetRecenzi: 22,
  },
  {
    slug: "akord-spravne",
    nazev: "Akord Správně s.r.o.",
    logo: logoBg("Akord", "7e22ce"),
    popis: "V harmonii s vaším domem. Důraz na komunikaci, mediaci sousedských sporů a férové schůze.",
    regionyPusobnosti: ["Praha 2", "Praha 3", "Praha 10"],
    pocetDomu: 52,
    pocetJednotek: 1320,
    rokZalozeni: 2014,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: true, onlineHlasovani: false, zkRekonstrukce: true, zkDotace: false, zkUvery: true, pravniPoradenstvi: true },
    cenaOd: 165,
    cenaDo: 235,
    kontaktniOsoba: "PhDr. Olga Marková",
    email: "info@akord.demo",
    telefon: "+420 222 711 711",
    web: "https://akord.demo",
    adresa: "Vinohradská 184, 130 00 Praha 3",
    reference: ["Mediace u 8 SVJ se sousedskými spory"],
    overeny: true, premium: false,
    prumerneHodnoceni: 4.5, pocetRecenzi: 19,
  },
  {
    slug: "byt-finance",
    nazev: "Byt Finance s.r.o.",
    logo: logoBg("Byt Finance", "047857"),
    popis: "Účetní firma, která rozšířila služby na komplexní správu SVJ. Naší silnou stránkou je daňová a účetní stránka.",
    regionyPusobnosti: ["Praha 4", "Praha 11", "Praha 12", "Praha 15"],
    pocetDomu: 88,
    pocetJednotek: 2680,
    rokZalozeni: 2006,
    sluzby: { ucetniSprava: true, technickaSprava: false, havarijniSluzba: false, onlinePortal: true, onlineHlasovani: false, zkRekonstrukce: false, zkDotace: true, zkUvery: true, pravniPoradenstvi: false },
    cenaOd: 120,
    cenaDo: 180,
    kontaktniOsoba: "Ing. Iva Pospíšilová",
    email: "info@bytfinance.demo",
    telefon: "+420 244 461 111",
    web: "https://bytfinance.demo",
    adresa: "Kongresová 2, 140 00 Praha 4",
    reference: ["88 SVJ s prošlými daňovými kontrolami bez závad"],
    overeny: true, premium: false,
    prumerneHodnoceni: 4.4, pocetRecenzi: 33,
  },
  {
    slug: "spravce-novak",
    nazev: "Správce Novák s.r.o.",
    logo: logoBg("Novak", "334155"),
    popis: "Rodinná firma třetí generace. Tradice od roku 1991. Osobní přístup, dlouholeté vztahy.",
    regionyPusobnosti: ["Praha 6", "Praha 7"],
    pocetDomu: 36,
    pocetJednotek: 980,
    rokZalozeni: 1991,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: false, onlineHlasovani: false, zkRekonstrukce: true, zkDotace: false, zkUvery: false, pravniPoradenstvi: false },
    cenaOd: 150,
    cenaDo: 200,
    kontaktniOsoba: "Antonín Novák",
    email: "info@spravcenovak.demo",
    telefon: "+420 233 322 211",
    web: "https://spravcenovak.demo",
    adresa: "Bubenečská 12, 160 00 Praha 6",
    reference: ["32 let nepřetržité spolupráce s SVJ v Bubenči a Dejvicích"],
    overeny: false, premium: false,
    prumerneHodnoceni: 4.2, pocetRecenzi: 16,
  },
  {
    slug: "primespravce",
    nazev: "PrimeSprávce s.r.o.",
    logo: logoBg("Prime", "1e1b4b"),
    popis: "Premium správa pro velké novostavby a developerské projekty. SLA 99,5 %, 24/7 dispečink.",
    regionyPusobnosti: ["Praha 5", "Praha 9", "Praha 8"],
    pocetDomu: 28,
    pocetJednotek: 1820,
    rokZalozeni: 2020,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: true, onlineHlasovani: true, zkRekonstrukce: true, zkDotace: true, zkUvery: true, pravniPoradenstvi: true },
    cenaOd: 220,
    cenaDo: 320,
    kontaktniOsoba: "Ing. David Brož",
    email: "info@primespravce.demo",
    telefon: "+420 226 555 100",
    web: "https://primespravce.demo",
    adresa: "Rohanské nábřeží 678, 186 00 Praha 8",
    reference: ["Rezidence Rohan — 312 jednotek", "Smíchov Yard — 184 j."],
    overeny: true, premium: true,
    prumerneHodnoceni: 4.8, pocetRecenzi: 17,
  },
  {
    slug: "spolecny-dum",
    nazev: "Společný dům s.r.o.",
    logo: logoBg("Spolecny", "9f1239"),
    popis: "Věříme, že dobré SVJ se pozná podle férových sousedských vztahů. Pomáháme tvořit funkční komunity.",
    regionyPusobnosti: ["Praha 3", "Praha 8", "Praha 10"],
    pocetDomu: 48,
    pocetJednotek: 1380,
    rokZalozeni: 2016,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: true, onlineHlasovani: true, zkRekonstrukce: true, zkDotace: true, zkUvery: false, pravniPoradenstvi: true },
    cenaOd: 175,
    cenaDo: 245,
    kontaktniOsoba: "Mgr. Veronika Šťastná",
    email: "info@spolecnydum.demo",
    telefon: "+420 222 818 818",
    web: "https://spolecnydum.demo",
    adresa: "Husitská 22, 130 00 Praha 3",
    reference: ["SVJ Žižkov Tower — 92 jednotek"],
    overeny: true, premium: false,
    prumerneHodnoceni: 4.6, pocetRecenzi: 23,
  },
  {
    slug: "spravce-online",
    nazev: "SprávceOnline s.r.o.",
    logo: logoBg("Online", "1d4ed8"),
    popis: "100 % digitální správa. Vše vyřídíte z mobilu. Žádné papíry, žádné cesty na úřad.",
    regionyPusobnosti: prahyVsechny,
    pocetDomu: 32,
    pocetJednotek: 980,
    rokZalozeni: 2022,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: false, onlinePortal: true, onlineHlasovani: true, zkRekonstrukce: false, zkDotace: false, zkUvery: false, pravniPoradenstvi: true },
    cenaOd: 180,
    cenaDo: 240,
    kontaktniOsoba: "Ing. Marek Doležal",
    email: "info@spravceonline.demo",
    telefon: "+420 800 555 100",
    web: "https://spravceonline.demo",
    adresa: "Karlovo náměstí 24, 120 00 Praha 2",
    reference: ["32 SVJ — 100 % bez papírů"],
    overeny: true, premium: true,
    prumerneHodnoceni: 4.7, pocetRecenzi: 13,
  },
  {
    slug: "stabilni-dum",
    nazev: "Stabilní dům s.r.o.",
    logo: logoBg("Stabilni Dum", "1e3a8a"),
    popis: "Stabilita, jistota, jasné smlouvy. Naším cílem je předvídatelnost a dlouhodobá spolupráce.",
    regionyPusobnosti: ["Praha 9", "Praha 10", "Praha 14", "Praha 18", "Praha 19"],
    pocetDomu: 124,
    pocetJednotek: 4180,
    rokZalozeni: 2002,
    sluzby: { ucetniSprava: true, technickaSprava: true, havarijniSluzba: true, onlinePortal: true, onlineHlasovani: false, zkRekonstrukce: true, zkDotace: true, zkUvery: true, pravniPoradenstvi: true },
    cenaOd: 145,
    cenaDo: 215,
    kontaktniOsoba: "Ing. Jiří Kubíček",
    email: "info@stabilnidum.demo",
    telefon: "+420 286 851 851",
    web: "https://stabilnidum.demo",
    adresa: "Sokolovská 1804, 190 00 Praha 9",
    reference: ["Průměrná doba spolupráce s klientem: 12 let"],
    overeny: true, premium: true,
    prumerneHodnoceni: 4.4, pocetRecenzi: 45,
  },
];
